import { LanguageCode } from '../types';

export interface LanguageInfo {
  code: LanguageCode;
  name: string;
  nativeName: string;
  speechCode: string;
  script: string;
}

export const SUPPORTED_LANGUAGES: LanguageInfo[] = [
  { code: 'en', name: 'English', nativeName: 'English', speechCode: 'en-IN', script: 'Latin' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', speechCode: 'te-IN', script: 'Telugu' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', speechCode: 'hi-IN', script: 'Devanagari' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', speechCode: 'kn-IN', script: 'Kannada' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', speechCode: 'ta-IN', script: 'Tamil' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം', speechCode: 'ml-IN', script: 'Malayalam' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी', speechCode: 'mr-IN', script: 'Devanagari' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', speechCode: 'bn-IN', script: 'Bengali' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી', speechCode: 'gu-IN', script: 'Gujarati' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ', speechCode: 'pa-IN', script: 'Gurmukhi' },
  { code: 'or', name: 'Odia', nativeName: 'ଓଡ଼ିଆ', speechCode: 'or-IN', script: 'Odia' },
  { code: 'as', name: 'Assamese', nativeName: 'অসমীয়া', speechCode: 'as-IN', script: 'Bengali' },
];

export interface UITranslation {
  appName: string;
  appSubtitle: string;
  navHome: string;
  navAsk: string;
  navGuided: string;
  navRights: string;
  navGrievance: string;
  navKnowledge: string;
  navVoice: string;
  navProfile: string;
  navSettings: string;
  welcomeHero: string;
  heroSubtitle: string;
  askCardTitle: string;
  askCardDesc: string;
  guidedCardTitle: string;
  guidedCardDesc: string;
  grievanceCardTitle: string;
  grievanceCardDesc: string;
  rightsCardTitle: string;
  rightsCardDesc: string;
  voiceCardTitle: string;
  voiceCardDesc: string;
  knowledgeCardTitle: string;
  knowledgeCardDesc: string;
  activeWorkflowNotice: string;
  resumeTaskBtn: string;
  sampleQuestionsLabel: string;
  typePlaceholder: string;
  sendBtn: string;
  voiceBtn: string;
  clearChatBtn: string;
  sourcesLabel: string;
  demoDataBadge: string;
  disclaimerText: string;
  closeBtn: string;
  backBtn: string;
  continueBtn: string;
  cancelBtn: string;
  saveBtn: string;
  editBtn: string;
  downloadPdfBtn: string;
  downloadTxtBtn: string;
  suggestedQ1: string;
  suggestedQ2: string;
  suggestedQ3: string;
  suggestedQ4: string;
  voiceListening: string;
  voiceProcessing: string;
  voiceSpeaking: string;
  voiceIdle: string;
}

export const TRANSLATIONS: Record<LanguageCode, UITranslation> = {
  en: {
    appName: 'Co-opSahayak',
    appSubtitle: 'AI-Powered Cooperative & Legal Helpdesk',
    navHome: 'Home',
    navAsk: 'Ask Assistant',
    navGuided: 'Guided Tasks',
    navRights: 'My Rights',
    navGrievance: 'File a Grievance',
    navKnowledge: 'Knowledge & Sources',
    navVoice: 'Voice Assistant',
    navProfile: 'My Profile',
    navSettings: 'Settings',
    welcomeHero: 'How can we help with your cooperative today?',
    heroSubtitle: 'Understand governance rules, member rights, elections, procedures, and draft official grievances with grounded cooperative bylaws.',
    askCardTitle: 'Ask a Question',
    askCardDesc: 'Get clear answers on laws, bylaws, rights, and voting rules.',
    guidedCardTitle: 'Guided Tasks',
    guidedCardDesc: 'Complete common cooperative procedures step-by-step.',
    grievanceCardTitle: 'File a Grievance',
    grievanceCardDesc: 'Prepare and document a structured formal grievance letter.',
    rightsCardTitle: 'My Rights',
    rightsCardDesc: 'Explore your statutory rights & governance responsibilities.',
    voiceCardTitle: 'Voice Assistant',
    voiceCardDesc: 'Speak naturally in your preferred regional language.',
    knowledgeCardTitle: 'Knowledge & Sources',
    knowledgeCardDesc: 'Inspect the bylaws, acts, and rules powering this assistant.',
    activeWorkflowNotice: 'You have an active in-progress task',
    resumeTaskBtn: 'Resume Task',
    sampleQuestionsLabel: 'Frequently Asked Cooperative Questions:',
    typePlaceholder: 'Ask in your language (e.g. Can I vote in cooperative election?)...',
    sendBtn: 'Send Query',
    voiceBtn: 'Voice Input',
    clearChatBtn: 'Clear Chat',
    sourcesLabel: 'Verified Sources & Citations',
    demoDataBadge: 'DEMO KNOWLEDGE BASE',
    disclaimerText: 'Notice: This assistant provides grounded informational guidance based on cooperative bylaws and acts. It does not replace official legal counsel.',
    closeBtn: 'Close',
    backBtn: 'Back',
    continueBtn: 'Continue',
    cancelBtn: 'Cancel',
    saveBtn: 'Save',
    editBtn: 'Edit',
    downloadPdfBtn: 'Download PDF',
    downloadTxtBtn: 'Download TXT',
    suggestedQ1: 'Can I vote in my cooperative election?',
    suggestedQ2: 'What are my rights as a cooperative society member?',
    suggestedQ3: 'How do I file a grievance against the managing committee?',
    suggestedQ4: 'What documents are required to register a cooperative?',
    voiceListening: 'Listening to your voice...',
    voiceProcessing: 'Understanding your request...',
    voiceSpeaking: 'Responding in your language...',
    voiceIdle: 'Tap microphone to speak',
  },
  te: {
    appName: 'కో-ఆప్ సహాయక్ (Co-opSahayak)',
    appSubtitle: 'సహకార & చట్టపరమైన సహాయ కేంద్రం (AI Helpdesk)',
    navHome: 'హోమ్',
    navAsk: 'సహాయకుడిని అడగండి',
    navGuided: 'మార్గదర్శక పనులు',
    navRights: 'నా హక్కులు',
    navGrievance: 'ఫిర్యాదు దాఖలు చేయండి',
    navKnowledge: 'చట్టాలు & నిబంధనలు',
    navVoice: 'వాయిస్ అసిస్టెంట్',
    navProfile: 'నా ప్రొఫైల్',
    navSettings: 'సెట్టింగ్‌లు',
    welcomeHero: 'సహకార సంఘ వ్యవహారాల్లో మీకు ఎలా సహాయపడగలం?',
    heroSubtitle: 'నిబంధనావళి, ఓటు హక్కులు, ఎన్నికలు మరియు అధికారిక ఫిర్యాదు పత్రాలను సులభంగా రూపొందించుకోండి.',
    askCardTitle: 'ప్రశ్న అడగండి',
    askCardDesc: 'నిబంధనలు, హక్కులు మరియు ఓటింగ్ నిబంధనలపై స్పష్టమైన సమాధానాలు పొందండి.',
    guidedCardTitle: 'మార్గదర్శక పనులు',
    guidedCardDesc: 'సాధారణ సహకార ప్రక్రియలను దశలవారీగా పూర్తి చేయండి.',
    grievanceCardTitle: 'ఫిర్యాదు దాఖలు చేయండి',
    grievanceCardDesc: 'అధికారిక నిబంధనలతో కూడిన ఫిర్యాదు పత్రాన్ని రూపొందించండి.',
    rightsCardTitle: 'నా హక్కులు',
    rightsCardDesc: 'మీ చట్టబద్ధమైన హక్కులు మరియు పాలన బాధ్యతలను తెలుసుకోండి.',
    voiceCardTitle: 'వాయిస్ అసిస్టెంట్',
    voiceCardDesc: 'మీ సొంత భాషలో సహజంగా మాట్లాడి సమాధానాలు పొందండి.',
    knowledgeCardTitle: 'చట్టాలు & మూలాలు',
    knowledgeCardDesc: 'సహాయక వ్యవస్థను నడిపించే ఉపనిబంధనలు మరియు చట్టాలను పరిశీలించండి.',
    activeWorkflowNotice: 'ప్రస్తుతం పురోగతిలో ఉన్న పని ఉంది',
    resumeTaskBtn: 'పనిని కొనసాగించండి',
    sampleQuestionsLabel: 'తరచుగా అడిగే ప్రశ్నలు:',
    typePlaceholder: 'మీ భాషలో అడగండి (ఉదా: నా ఓటు హక్కు ఏంటి?)...',
    sendBtn: 'పంపు',
    voiceBtn: 'వాయిస్ ఇన్‌పుట్',
    clearChatBtn: 'చాట్ క్లియర్ చేయి',
    sourcesLabel: 'ధృవీకరించబడిన మూలాలు',
    demoDataBadge: 'డెమో నాలెడ్జ్ బేస్',
    disclaimerText: 'గమనిక: ఈ సహాయకుడు సహకార ఉపనిబంధనల ఆధారంగా మార్గదర్శకత్వాన్ని అందిస్తుంది. ఇది న్యాయవాద సలహాకు ప్రత్యామ్నాయం కాదు.',
    closeBtn: 'మూసివేయి',
    backBtn: 'వెనుకకు',
    continueBtn: 'కొనసాగించు',
    cancelBtn: 'రద్దు చేయి',
    saveBtn: 'సేవ్ చేయి',
    editBtn: 'సవరించు',
    downloadPdfBtn: 'PDF డౌన్‌లోడ్',
    downloadTxtBtn: 'TXT డౌన్‌లోడ్',
    suggestedQ1: 'నా ఓటు హక్కు ఏంటి?',
    suggestedQ2: 'సభ్యుడిగా నా హక్కులు ఏమిటి?',
    suggestedQ3: 'కమిటీపై ఫిర్యాదు చేయడం ఎలా?',
    suggestedQ4: 'సహకార సంఘం రిజిస్ట్రేషన్ పత్రాలు ఏవి?',
    voiceListening: 'వింటున్నాము...',
    voiceProcessing: 'విశ్లేషిస్తున్నాము...',
    voiceSpeaking: 'సమాధానం ఇస్తున్నాము...',
    voiceIdle: 'మాట్లాడటానికి మైక్ నొక్కండి',
  },
  hi: {
    appName: 'को-ऑप सहायक (Co-opSahayak)',
    appSubtitle: 'सहकारी एवं कानूनी सहायता केंद्र (AI Helpdesk)',
    navHome: 'होम',
    navAsk: 'सहायक से पूछें',
    navGuided: 'मार्गदर्शित कार्य',
    navRights: 'मेरे अधिकार',
    navGrievance: 'शिकायत दर्ज करें',
    navKnowledge: 'दस्तावेज़ व स्रोत',
    navVoice: 'वॉयस सहायक',
    navProfile: 'मेरी प्रोफ़ाइल',
    navSettings: 'सेटिंग्स',
    welcomeHero: 'आज हम आपकी सहकारी समिति में कैसे सहायता कर सकते हैं?',
    heroSubtitle: 'सहकारी उप-नियमों, मतदान अधिकारों, चुनाव नियमों को समझें और औपचारिक शिकायत पत्र तैयार करें।',
    askCardTitle: 'प्रश्न पूछें',
    askCardDesc: 'कानूनों, उप-नियमों, अधिकारों और मतदान नियमों पर स्पष्ट उत्तर पाएं।',
    guidedCardTitle: 'मार्गदर्शित कार्य',
    guidedCardDesc: 'सामान्य सहकारी प्रक्रियाओं को चरण-दर-चरण पूरा करें।',
    grievanceCardTitle: 'शिकायत दर्ज करें',
    grievanceCardDesc: 'नियमों पर आधारित एक संरचित औपचारिक शिकायत पत्र तैयार करें।',
    rightsCardTitle: 'मेरे अधिकार',
    rightsCardDesc: 'अपने वैधानिक अधिकारों और जिम्मेदारियों को जानें।',
    voiceCardTitle: 'वॉयस सहायक',
    voiceCardDesc: 'अपनी पसंदीदा क्षेत्रीय भाषा में सहजता से बोलें।',
    knowledgeCardTitle: 'दस्तावेज़ व स्रोत',
    knowledgeCardDesc: 'सहकारी अधिनियमों और नियमों का निरीक्षण करें।',
    activeWorkflowNotice: 'आपके पास एक सक्रिय कार्य प्रगति पर है',
    resumeTaskBtn: 'कार्य जारी रखें',
    sampleQuestionsLabel: 'अक्सर पूछे जाने वाले प्रश्न:',
    typePlaceholder: 'अपनी भाषा में पूछें (उदा. क्या मैं सहकारी चुनाव में वोट दे सकता हूँ?)...',
    sendBtn: 'भेजें',
    voiceBtn: 'वॉयस इनपुट',
    clearChatBtn: 'चैट साफ़ करें',
    sourcesLabel: 'सत्यापित स्रोत और संदर्भ',
    demoDataBadge: 'डेमो नॉलेज बेस',
    disclaimerText: 'सूचना: यह सहायक सहकारी उप-नियमों पर आधारित सूचनात्मक मार्गदर्शन प्रदान करता है। यह कानूनी सलाह का विकल्प नहीं है।',
    closeBtn: 'बंद करें',
    backBtn: 'पीछे',
    continueBtn: 'जारी रखें',
    cancelBtn: 'रद्द करें',
    saveBtn: 'सहेजें',
    editBtn: 'संपादित करें',
    downloadPdfBtn: 'PDF डाउनलोड करें',
    downloadTxtBtn: 'TXT डाउनलोड करें',
    suggestedQ1: 'क्या मैं चुनाव में वोट दे सकता हूँ?',
    suggestedQ2: 'सदस्य के रूप में मेरे क्या अधिकार हैं?',
    suggestedQ3: 'प्रबंध समिति के विरुद्ध शिकायत कैसे दर्ज करें?',
    suggestedQ4: 'सहकारी समिति पंजीकरण के लिए क्या दस्तावेज़ चाहिए?',
    voiceListening: 'सुन रहे हैं...',
    voiceProcessing: 'समझ रहे हैं...',
    voiceSpeaking: 'उत्तर दे रहे हैं...',
    voiceIdle: 'बोलने के लिए माइक दबाएं',
  },
  kn: {
    appName: 'ಕೋ-ಆಪ್ ಸಹಾಯಕ (Co-opSahayak)',
    appSubtitle: 'ಸಹಕಾರಿ ಮತ್ತು ಕಾನೂನು ಸಹಾಯ ಕೇಂದ್ರ',
    navHome: 'ಮುಖಪುಟ',
    navAsk: 'ಸಹಾಯಕರನ್ನು ಕೇಳಿ',
    navGuided: 'ಮಾರ್ಗದರ್ಶಿತ ಕಾರ್ಯಗಳು',
    navRights: 'ನನ್ನ ಹಕ್ಕುಗಳು',
    navGrievance: 'ದೂರು ಸಲ್ಲಿಸಿ',
    navKnowledge: 'ಮೂಲಗಳು ಮತ್ತು ನಿಯಮಗಳು',
    navVoice: 'ಧ್ವನಿ ಸಹಾಯಕ',
    navProfile: 'ನನ್ನ ಪ್ರೊಫೈಲ್',
    navSettings: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    welcomeHero: 'ಇಂದು ನಿಮ್ಮ ಸಹಕಾರ ಸಂಘದ ವಿಷಯದಲ್ಲಿ ನಾವು ಹೇಗೆ ಸಹಾಯ ಮಾಡಬಹುದು?',
    heroSubtitle: 'ಆಡಳಿತ ನಿಯಮಗಳು, ಸದಸ್ಯರ ಹಕ್ಕುಗಳು, ಚುನಾವಣೆಗಳು ಮತ್ತು ಅಧಿಕೃತ ದೂರು ಪತ್ರಗಳನ್ನು ಸುಲಭವಾಗಿ ಸಿದ್ಧಪಡಿಸಿ.',
    askCardTitle: 'ಪ್ರಶ್ನೆ ಕೇಳಿ',
    askCardDesc: 'ಕಾನೂನುಗಳು ಮತ್ತು ಮತದಾನ ನಿಯಮಗಳ ಬಗ್ಗೆ ಸ್ಪಷ್ಟ ಉತ್ತರಗಳನ್ನು ಪಡೆಯಿರಿ.',
    guidedCardTitle: 'ಮಾರ್ಗದರ್ಶಿತ ಕಾರ್ಯಗಳು',
    guidedCardDesc: 'ಸಾಮಾನ್ಯ ಸಹಕಾರಿ ಪ್ರಕ್ರಿಯೆಗಳನ್ನು ಹಂತ ಹಂತವಾಗಿ ಪೂರ್ಣಗೊಳಿಸಿ.',
    grievanceCardTitle: 'ದೂರು ಸಲ್ಲಿಸಿ',
    grievanceCardDesc: 'ನಿಯಮಬದ್ಧವಾದ ಅಧಿಕೃತ ದೂರು ಪತ್ರವನ್ನು ರಚಿಸಿ.',
    rightsCardTitle: 'ನನ್ನ ಹಕ್ಕುಗಳು',
    rightsCardDesc: 'ನಿಮ್ಮ ಶಾಸನಬದ್ಧ ಹಕ್ಕುಗಳು ಮತ್ತು ಜವಾಬ್ದಾರಿಗಳನ್ನು ಪರಿಶೀಲಿಸಿ.',
    voiceCardTitle: 'ಧ್ವನಿ ಸಹಾಯಕ',
    voiceCardDesc: 'ನಿಮ್ಮ ಮಾತೃಭಾಷೆಯಲ್ಲಿ ಮುಕ್ತವಾಗಿ ಮಾತನಾಡಿ.',
    knowledgeCardTitle: 'ಮೂಲಗಳು ಮತ್ತು ನಿಯಮಗಳು',
    knowledgeCardDesc: 'ಸಹಕಾರಿ ಬೈಲಾ ಮತ್ತು ಕಾಯ್ದೆಗಳನ್ನು ವೀಕ್ಷಿಸಿ.',
    activeWorkflowNotice: 'ನಿಮ್ಮ ಒಂದು ಕಾರ್ಯ ಪ್ರಗತಿಯಲ್ಲಿದೆ',
    resumeTaskBtn: 'ಮುಂದುವರಿಸಿ',
    sampleQuestionsLabel: 'ಪದೇ ಪದೇ ಕೇಳಲಾಗುವ ಪ್ರಶ್ನೆಗಳು:',
    typePlaceholder: 'ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ ಕೇಳಿ (ಉದಾ: ನನ್ನ ಓಟು ಹಕ್ಕು ಏನು?)...',
    sendBtn: 'ಕಳುಹಿಸಿ',
    voiceBtn: 'ಧ್ವನಿ ಇನ್‌ಪುಟ್',
    clearChatBtn: 'ಚಾಟ್ ತೆರವುಗೊಳಿಸಿ',
    sourcesLabel: 'ಪರಿಶೀಲಿಸಿದ ಆಧಾರಗಳು',
    demoDataBadge: 'ಡೆಮೊ ಮಾಹಿತಿ ಕೋಶ',
    disclaimerText: 'ಸೂಚನೆ: ಇದು ಕೇವಲ ಮಾಹಿತಿ ಮಾರ್ಗದರ್ಶನವಾಗಿದೆ, ವಕೀಲರ ಅಧಿಕೃತ ಸಲಹೆಗೆ ಬದಲಿಯಲ್ಲ.',
    closeBtn: 'ಮುಚ್ಚಿ',
    backBtn: 'ಹಿಂದೆ',
    continueBtn: 'ಮುಂದುವರಿಸಿ',
    cancelBtn: 'ರದ್ದುಮಾಡಿ',
    saveBtn: 'ಉಳಿಸಿ',
    editBtn: 'ತಿದ್ದಿ',
    downloadPdfBtn: 'PDF ಡೌನ್‌ಲೋಡ್',
    downloadTxtBtn: 'TXT ಡೌನ್‌ಲೋಡ್',
    suggestedQ1: 'ನನ್ನ ಮತದಾನದ ಹಕ್ಕು ಏನು?',
    suggestedQ2: 'ಸದಸ್ಯನಾಗಿ ನನ್ನ ಹಕ್ಕುಗಳೇನು?',
    suggestedQ3: 'ಸಮಿತಿಯ ವಿರುದ್ಧ ದೂರು ದಾಖಲಿಸುವುದು ಹೇಗೆ?',
    suggestedQ4: 'ಸಹಕಾರ ಸಂಘ ನೋಂದಣಿಗೆ ಬೇಕಾಗುವ ದಾಖಲೆಗಳೇನು?',
    voiceListening: 'ಕೇಳಿಸಿಕೊಳ್ಳುತ್ತಿದ್ದೇವೆ...',
    voiceProcessing: 'ಪರಿಶೀಲಿಸುತ್ತಿದ್ದೇವೆ...',
    voiceSpeaking: 'ಉತ್ತರಿಸುತ್ತಿದ್ದೇವೆ...',
    voiceIdle: 'ಮಾತನಾಡಲು ಮೈಕ್ ಒತ್ತಿ',
  },
  ta: {
    appName: 'கோ-ஆப் சஹாயக் (Co-opSahayak)',
    appSubtitle: 'கூட்டுறவு மற்றும் சட்ட உதவி மையம்',
    navHome: 'முகப்பு',
    navAsk: 'உதவியாளரிடம் கேளுங்கள்',
    navGuided: 'வழிகாட்டப்பட்ட பணிகள்',
    navRights: 'எனது உரிமைகள்',
    navGrievance: 'புகார் அளிக்கவும்',
    navKnowledge: 'ஆவணங்கள் மற்றும் சட்டங்கள்',
    navVoice: 'குரல் உதவியாளர்',
    navProfile: 'எனது விவரக்குறிப்பு',
    navSettings: 'அமைப்புகள்',
    welcomeHero: 'உங்கள் கூட்டுறவு சங்கத்திற்கு இன்று எவ்வாறு உதவலாம்?',
    heroSubtitle: 'நிர்வாக விதிகள், உறுப்பினர் உரிமைகள், தேர்தல் நடைமுறைகள் மற்றும் அதிகாரப்பூர்வ புகார் கடிதங்களை உருவாக்கவும்.',
    askCardTitle: 'கேள்வி கேளுங்கள்',
    askCardDesc: 'விதிகள், உரிமைகள் மற்றும் வாக்குப்பதிவு பற்றிய தெளிவான பதில்களைப் பெறுங்கள்.',
    guidedCardTitle: 'வழிகாட்டப்பட்ட பணிகள்',
    guidedCardDesc: 'கூட்டுறவு நடைமுறைகளை படிப்படியாக முடிக்கவும்.',
    grievanceCardTitle: 'புகார் அளிக்கவும்',
    grievanceCardDesc: 'சட்டபூர்வ புகார் கடிதத்தை எளிதாகத் தயாரிக்கவும்.',
    rightsCardTitle: 'எனது உரிமைகள்',
    rightsCardDesc: 'உங்கள் சட்டப்பூர்வ உரிமைகளை அறிந்து கொள்ளுங்கள்.',
    voiceCardTitle: 'குரல் உதவியாளர்',
    voiceCardDesc: 'உங்கள் சொந்த மொழியில் பேசி பதில் பெறுங்கள்.',
    knowledgeCardTitle: 'ஆவணங்கள் மற்றும் சட்டங்கள்',
    knowledgeCardDesc: 'கூட்டுறவு விதிகள் மற்றும் சட்டங்களை ஆய்வு செய்யுங்கள்.',
    activeWorkflowNotice: 'தற்போது ஒரு பணி நிலுவையில் உள்ளது',
    resumeTaskBtn: 'தொடரவும்',
    sampleQuestionsLabel: 'அடிக்கடி கேட்கப்படும் கேள்விகள்:',
    typePlaceholder: 'உங்கள் மொழியில் கேளுங்கள் (उदा. எனது வாக்கு உரிமை என்ன?)...',
    sendBtn: 'அனுப்புக',
    voiceBtn: 'குரல் உள்ளீடு',
    clearChatBtn: 'அரட்டையை அழிக்கவும்',
    sourcesLabel: 'சரிபார்க்கப்பட்ட ஆதாரங்கள்',
    demoDataBadge: 'டெமோ தகவல் தளம்',
    disclaimerText: 'குறிப்பு: இது கூட்டுறவு விதிகளின் அடிப்படையிலான தகவல் மட்டுமே. சட்ட ஆலோசகரின் மாற்றாகாது.',
    closeBtn: 'மூடு',
    backBtn: 'பின்செல்',
    continueBtn: 'தொடர்க',
    cancelBtn: 'ரத்துசெய்',
    saveBtn: 'சேமி',
    editBtn: 'திருத்து',
    downloadPdfBtn: 'PDF பதிவிறக்கம்',
    downloadTxtBtn: 'TXT பதிவிறக்கம்',
    suggestedQ1: 'எனது வாக்கு உரிமை என்ன?',
    suggestedQ2: 'உறுப்பினராக எனது உரிமைகள் என்ன?',
    suggestedQ3: 'நிர்வாகக் குழுவிற்கு எதிராக புகார் செய்வது எப்படி?',
    suggestedQ4: 'கூட்டுறவு சங்கம் பதிவு செய்ய தேவையான ஆவணங்கள் என்ன?',
    voiceListening: 'கேட்கிறது...',
    voiceProcessing: 'செயலாக்குகிறது...',
    voiceSpeaking: 'பதிலளிக்கிறது...',
    voiceIdle: 'பேச மைக்-ஐ அழுத்தவும்',
  },
  mr: {
    appName: 'को-ऑप सहाय्यक (Co-opSahayak)',
    appSubtitle: 'सहकारी व कायदेशीर मदत केंद्र',
    navHome: 'मुख्यपृष्ठ',
    navAsk: 'सहाय्यकाला विचारा',
    navGuided: 'मार्गदर्शित कार्ये',
    navRights: 'माझे हक्क',
    navGrievance: 'तक्रार दाखल करा',
    navKnowledge: 'नियम व स्रोत',
    navVoice: 'व्हॉइस असिस्टंट',
    navProfile: 'माझे प्रोफाइल',
    navSettings: 'सेटिंग्ज',
    welcomeHero: 'आज आम्ही आपल्या सहकारी संस्थेसाठी कशी मदत करू शकतो?',
    heroSubtitle: 'प्रशासकीय नियम, सभासदांचे हक्क, निवडणूक प्रक्रिया आणि अधिकृत तक्रार अर्ज सहज तयार करा.',
    askCardTitle: 'प्रश्न विचारा',
    askCardDesc: 'उपनियम, कायदे आणि मतदान नियमांवर स्पष्ट उत्तरे मिळवा.',
    guidedCardTitle: 'मार्गदर्शित कार्ये',
    guidedCardDesc: 'सर्वसामान्य सहकारी प्रक्रिया टप्प्याटप्प्याने पूर्ण करा.',
    grievanceCardTitle: 'तक्रार दाखल करा',
    grievanceCardDesc: 'उपनियमांवर आधारित अधिकृत तक्रार पत्र तयार करा.',
    rightsCardTitle: 'माझे हक्क',
    rightsCardDesc: 'आपले वैधानिक हक्क आणि जबाबदाऱ्या तपासा.',
    voiceCardTitle: 'व्हॉइस असिस्टंट',
    voiceCardDesc: 'आपल्या स्वतःच्या भाषेत सहजतेने बोला.',
    knowledgeCardTitle: 'नियम व स्रोत',
    knowledgeCardDesc: 'सहकारी कायदे व उपनियमांचे निरीक्षण करा.',
    activeWorkflowNotice: 'आपले एक कार्य प्रगतीपथावर आहे',
    resumeTaskBtn: 'कार्य सुरू ठेवा',
    sampleQuestionsLabel: 'वारंवार विचारले जाणारे प्रश्न:',
    typePlaceholder: 'आपल्या भाषेत विचारा (उदा. माझा मतदानाचा हक्क काय आहे?)...',
    sendBtn: 'पाठवा',
    voiceBtn: 'व्हॉइस इनपुट',
    clearChatBtn: 'चॅट साफ करा',
    sourcesLabel: 'प्रमाणित स्रोत व संदर्भ',
    demoDataBadge: 'डेमो नॉलेज बेस',
    disclaimerText: 'सूचना: हा सहाय्यक सहकारी उपनियमांवर आधारित माहिती देतो. हा कायदेशीर सल्ल्याचा पर्याय नाही.',
    closeBtn: 'बंद करा',
    backBtn: 'मागे',
    continueBtn: 'पुढे जा',
    cancelBtn: 'रद्द करा',
    saveBtn: 'जतन करा',
    editBtn: 'संपादित करा',
    downloadPdfBtn: 'PDF डाउनलोड',
    downloadTxtBtn: 'TXT डाउनलोड',
    suggestedQ1: 'माझा मतदानाचा हक्क काय आहे?',
    suggestedQ2: 'सभासद म्हणून माझे काय हक्क आहेत?',
    suggestedQ3: 'व्यवस्थापक समितीविरुद्ध तक्रार कशी करावी?',
    suggestedQ4: 'सहकारी संस्था नोंदणीसाठी कोणती कागदपत्रे लागतात?',
    voiceListening: 'ऐकत आहोत...',
    voiceProcessing: 'समजून घेत आहोत...',
    voiceSpeaking: 'उत्तर देत आहोत...',
    voiceIdle: 'बोलण्यासाठी माइक दाबा',
  },
  bn: {
    appName: 'কো-অপ সহায়ক (Co-opSahayak)',
    appSubtitle: 'সমবায় এবং আইনি সহায়তা কেন্দ্র',
    navHome: 'হোম',
    navAsk: 'সহায়ককে জিজ্ঞাসা করুন',
    navGuided: 'নির্দেশিত কাজ',
    navRights: 'আমার অধিকার',
    navGrievance: 'অভিযোগ দায়ের করুন',
    navKnowledge: 'আইন ও উৎস',
    navVoice: 'ভয়েস সহকারী',
    navProfile: 'আমার প্রোফাইল',
    navSettings: 'সেটিংস',
    welcomeHero: 'আজ আপনার সমবায় সংক্রান্ত বিষয়ে আমরা কীভাবে সাহায্য করতে পারি?',
    heroSubtitle: 'নিয়মাবলী, সদস্য অধিকার, নির্বাচন প্রক্রিয়া বুঝুন এবং দাপ্তরিক অভিযোগপত্র তৈরি করুন।',
    askCardTitle: 'প্রশ্ন জিজ্ঞাসা করুন',
    askCardDesc: 'আইন ও ভোটিং নিয়মের স্পষ্ট উত্তর পান।',
    guidedCardTitle: 'নির্দেশিত কাজ',
    guidedCardDesc: 'সাধারণ সমবায় প্রক্রিয়া ধাপে ধাপে সম্পন্ন করুন।',
    grievanceCardTitle: 'অভিযোগ দায়ের করুন',
    grievanceCardDesc: 'নিয়মভিত্তিক আনুষ্ঠানিক অভিযোগপত্র তৈরি করুন।',
    rightsCardTitle: 'আমার অধিকার',
    rightsCardDesc: 'আপনার আইনি অধিকার ও দায়িত্বগুলি জানুন।',
    voiceCardTitle: 'ভয়েস সহকারী',
    voiceCardDesc: 'নিজের ভাষায় কথা বলুন এবং উত্তর শুনুন।',
    knowledgeCardTitle: 'আইন ও উৎস',
    knowledgeCardDesc: 'সমবায় উপ-আইন ও নথি পরিদর্শন করুন।',
    activeWorkflowNotice: 'আপনার একটি কাজ প্রক্রিয়াধীন আছে',
    resumeTaskBtn: 'কাজ চালিয়ে যান',
    sampleQuestionsLabel: 'সাধারণ প্রশ্নসমূহ:',
    typePlaceholder: 'আপনার ভাষায় জিজ্ঞাসা করুন (যেমন: আমার ভোটের অধিকার কী?)...',
    sendBtn: 'পাঠান',
    voiceBtn: 'ভয়েস ইনপুট',
    clearChatBtn: 'চ্যাট পরিষ্কার করুন',
    sourcesLabel: 'যাচাইকৃত উৎসসমূহ',
    demoDataBadge: 'ডেমো জ্ঞান ভাণ্ডার',
    disclaimerText: 'বিজ্ঞপ্তি: এটি সমবায় উপ-আইন ভিত্তিক তথ্য প্রদান করে, কোনও আইনি পরামর্শের বিকল্প নয়।',
    closeBtn: 'বন্ধ করুন',
    backBtn: 'পেছনে',
    continueBtn: 'চালিয়ে যান',
    cancelBtn: 'বাতিল',
    saveBtn: 'সংরক্ষণ',
    editBtn: 'সম্পাদনা',
    downloadPdfBtn: 'PDF ডাউনলোড',
    downloadTxtBtn: 'TXT ডাউনলোড',
    suggestedQ1: 'আমার ভোটের অধিকার কী?',
    suggestedQ2: 'সদস্য হিসেবে আমার কী অধিকার আছে?',
    suggestedQ3: 'কমিটির বিরুদ্ধে কীভাবে অভিযোগ করব?',
    suggestedQ4: 'সমবায় নিবন্ধনের জন্য প্রয়োজনীয় নথি কী?',
    voiceListening: 'শুনছি...',
    voiceProcessing: 'প্রক্রিয়াকরণ হচ্ছে...',
    voiceSpeaking: 'উত্তর দিচ্ছি...',
    voiceIdle: 'কথা বলতে মাইকে চাপ দিন',
  },
  ml: {
    appName: 'കോ-ഓപ്പ് സഹായക് (Co-opSahayak)',
    appSubtitle: 'സഹകരണ നിയമ സഹായ കേന്ദ്രം',
    navHome: 'ഹോം',
    navAsk: 'സഹായകനോട് ചോദിക്കുക',
    navGuided: 'പ്രക്രിയകൾ',
    navRights: 'എന്റെ അവകാശങ്ങൾ',
    navGrievance: 'പരാതി നൽകുക',
    navKnowledge: 'നിയമങ്ങളും ഉറവിടങ്ങളും',
    navVoice: 'വോയ്‌സ് അസിസ്റ്റന്റ്',
    navProfile: 'എന്റെ പ്രൊഫൈൽ',
    navSettings: 'ക്രമീകരണങ്ങൾ',
    welcomeHero: 'നിങ്ങളുടെ സഹകരണ സംഘവുമായി ബന്ധപ്പെട്ട് ഇന്ന് എങ്ങനെ സഹായിക്കണം?',
    heroSubtitle: 'നിയമങ്ങൾ, അംഗങ്ങളുടെ അവകാശങ്ങൾ, തിരഞ്ഞെടുപ്പ് നടപടികൾ എന്നിവ മനസ്സിലാക്കി ഔദ്യോഗിക പരാതി തയ്യാറാക്കൂ.',
    askCardTitle: 'ചോദ്യം ചോദിക്കുക',
    askCardDesc: 'ഉപനിയമങ്ങളും വോട്ടവകാശ നിയമങ്ങളും കൃത്യമായി മനസ്സിലാക്കൂ.',
    guidedCardTitle: 'പ്രക്രിയകൾ',
    guidedCardDesc: 'സഹകരണ നടപടിക്രമങ്ങൾ ഘട്ടം ഘട്ടമായി പൂർത്തിയാക്കുക.',
    grievanceCardTitle: 'പരാതി നൽകുക',
    grievanceCardDesc: 'ഔദ്യോഗിക പരാതി പത്രിക എളുപ്പത്തിൽ തയ്യാറാക്കുക.',
    rightsCardTitle: 'എന്റെ അവകാശങ്ങൾ',
    rightsCardDesc: 'നിങ്ങളുടെ നിയമപരമായ അവകാശങ്ങൾ പരിശോധിക്കുക.',
    voiceCardTitle: 'വോയ്‌സ് അസിസ്റ്റന്റ്',
    voiceCardDesc: 'നിങ്ങളുടെ മാതൃഭാഷയിൽ സംസാരിച്ച് മറുപടി നേടൂ.',
    knowledgeCardTitle: 'നിയമങ്ങളും ഉറവിടങ്ങളും',
    knowledgeCardDesc: 'സഹകരണ നിയമ രേഖകൾ പരിശോധിക്കുക.',
    activeWorkflowNotice: 'ഒരു പ്രക്രിയ പുരോഗതിയിലാണ്',
    resumeTaskBtn: 'തുടരുക',
    sampleQuestionsLabel: 'സാധാരണ ചോദ്യങ്ങൾ:',
    typePlaceholder: 'മലയാളത്തിൽ ചോദിക്കുക (ഉദാ: എന്റെ വോട്ടവകാശം എന്താണ്?)...',
    sendBtn: 'അയക്കുക',
    voiceBtn: 'വോയ്‌സ് ഇൻപുട്ട്',
    clearChatBtn: 'ചാറ്റ് ക്ലിയർ ചെയ്യുക',
    sourcesLabel: 'സ്ഥിരീകരിച്ച ഉറവിടങ്ങൾ',
    demoDataBadge: 'ഡെമോ നോളജ് ബേസ്',
    disclaimerText: 'ശ്രദ്ധിക്കുക: ഇത് ഉപനിയമങ്ങളെ അടിസ്ഥാനമാക്കിയുള്ള വിവരങ്ങൾ മാത്രമാണ്, ഔദ്യോഗിക നിയമോപദേശമല്ല.',
    closeBtn: 'അടയ്ക്കുക',
    backBtn: 'പിന്നോട്ട്',
    continueBtn: 'തുടരുക',
    cancelBtn: 'റദ്ദാക്കുക',
    saveBtn: 'സേവ് ചെയ്യുക',
    editBtn: 'മാറ്റം വരുത്തുക',
    downloadPdfBtn: 'PDF ഡൗൺലോഡ്',
    downloadTxtBtn: 'TXT ഡൗൺലോഡ്',
    suggestedQ1: 'എന്റെ വോട്ടവകാശം എന്താണ്?',
    suggestedQ2: 'അംഗമെന്ന നിലയിലുള്ള അവകാശങ്ങൾ എന്തൊക്കെ?',
    suggestedQ3: 'കമ്മിറ്റിക്കെതിരെ പരാതി നൽകുന്നത് എങ്ങനെ?',
    suggestedQ4: 'സംഘം രജിസ്റ്റർ ചെയ്യാൻ വേണ്ട രേഖകൾ ഏവ?',
    voiceListening: 'കേൾക്കുന്നു...',
    voiceProcessing: 'മനസ്സിലാക്കുന്നു...',
    voiceSpeaking: 'മറുപടി നൽകുന്നു...',
    voiceIdle: 'സംസാരിക്കാൻ മൈക്ക് അമർത്തുക',
  },
  gu: {
    appName: 'કો-ઓપ સહાયક (Co-opSahayak)',
    appSubtitle: 'સહકારી અને કાનૂની સહાયતા કેન્દ્ર',
    navHome: 'હોમ',
    navAsk: 'સહાયકને પૂછો',
    navGuided: 'માર્ગદર્શિત કાર્યો',
    navRights: 'મારા અધિકારો',
    navGrievance: 'ફરિયાદ નોંધાવો',
    navKnowledge: 'નિયમો અને સ્ત્રોતો',
    navVoice: 'વોઇસ સહાયક',
    navProfile: 'મારી પ્રોફાઇલ',
    navSettings: 'સેટિંગ્સ',
    welcomeHero: 'આજે અમે તમારી સહકારી મંડળીમાં કેવી રીતે મદદ કરી શકીએ?',
    heroSubtitle: 'ઉપ-નિયમો, મતદાન અધિકારો, ચૂંટણી પ્રક્રિયા સમજો અને સત્તાવાર ફરિયાદ પત્ર તૈયાર કરો.',
    askCardTitle: 'પ્રશ્ન પૂછો',
    askCardDesc: 'કાયદા, ઉપ-નિયમો અને મતદાન નિયમો પર સ્પષ્ટ જવાબો મેળવો.',
    guidedCardTitle: 'માર્ગદર્શિત કાર્યો',
    guidedCardDesc: 'સામાન્ય સહકારી પ્રક્રિયાઓ પગલાંવાર પૂર્ણ કરો.',
    grievanceCardTitle: 'ફરિયાદ નોંધાવો',
    grievanceCardDesc: 'નિયમબદ્ધ ઔપચારિક ફરિયાદ પત્ર તૈયાર કરો.',
    rightsCardTitle: 'મારા અધિકારો',
    rightsCardDesc: 'તમારા વૈધાનિક અધિકારો અને જવાબદારીઓ તપાસો.',
    voiceCardTitle: 'વોઇસ સહાયક',
    voiceCardDesc: 'તમારી પોતાની ભાષામાં બોલીને જવાબ મેળવો.',
    knowledgeCardTitle: 'નિયમો અને સ્ત્રોતો',
    knowledgeCardDesc: 'સહકારી કાયદાઓ અને પુસ્તકોનું નિરીક્ષણ કરો.',
    activeWorkflowNotice: 'તમારું એક કાર્ય ચાલુ છે',
    resumeTaskBtn: 'કાર્ય ચાલુ રાખો',
    sampleQuestionsLabel: 'વારંવાર પૂછાતા પ્રશ્નો:',
    typePlaceholder: 'તમારી ભાષામાં પૂછો (દા.ત. મારો મત આપવાનો અધિકાર શું છે?)...',
    sendBtn: 'મોકલો',
    voiceBtn: 'વોઇસ ઇનપુટ',
    clearChatBtn: 'ચેટ સાફ કરો',
    sourcesLabel: 'ચકાસાયેલ સ્ત્રોતો',
    demoDataBadge: 'ડેમો નોલેજ બેઝ',
    disclaimerText: 'નોંધ: આ સહાયક ઉપ-નિયમો આધારિત માહિતી આપે છે. તે કાનૂની સલાહનો વિકલ્પ નથી.',
    closeBtn: 'બંધ કરો',
    backBtn: 'પાછળ',
    continueBtn: 'ચાલુ રાખો',
    cancelBtn: 'રદ કરો',
    saveBtn: 'સાચવો',
    editBtn: 'સુધારો',
    downloadPdfBtn: 'PDF ડાઉનલોડ',
    downloadTxtBtn: 'TXT ડાઉનલોડ',
    suggestedQ1: 'મારો મત આપવાનો અધિકાર શું છે?',
    suggestedQ2: 'સભ્ય તરીકે મારા અધિકારો શું છે?',
    suggestedQ3: 'કમિટી વિરુદ્ધ ફરિયાદ કેવી રીતે કરવી?',
    suggestedQ4: 'મંડળીની નોંધણી માટે કયા દસ્તાવેજો જરૂરી છે?',
    voiceListening: 'સાંભળી રહ્યા છીએ...',
    voiceProcessing: 'સમજી રહ્યા છીએ...',
    voiceSpeaking: 'જવાબ આપી રહ્યા છીએ...',
    voiceIdle: 'બોલવા માટે માઇક દબાવો',
  },
  pa: {
    appName: 'ਕੋ-ਆਪ ਸਹਾਇਕ (Co-opSahayak)',
    appSubtitle: 'ਸਹਿਕਾਰੀ ਅਤੇ ਕਾਨੂੰਨੀ ਸਹਾਇਤਾ ਕੇਂਦਰ',
    navHome: 'ਮੁੱਖ ਪੰਨਾ',
    navAsk: 'ਸਹਾਇਕ ਨੂੰ ਪੁੱਛੋ',
    navGuided: 'ਮਾਰਗਦਰਸ਼ਨ ਕਾਰਜ',
    navRights: 'ਮੇਰੇ ਅਧਿਕਾਰ',
    navGrievance: 'ਸ਼ਿਕਾਇਤ ਦਰਜ ਕਰੋ',
    navKnowledge: 'ਨਿਯਮ ਅਤੇ ਸਰੋਤ',
    navVoice: 'ਆਵਾਜ਼ ਸਹਾਇਕ',
    navProfile: 'ਮੇਰਾ ਪ੍ਰੋਫਾਈਲ',
    navSettings: 'ਸੈਟਿੰਗਾਂ',
    welcomeHero: 'ਅੱਜ ਅਸੀਂ ਤੁਹਾਡੀ ਸਹਿਕਾਰੀ ਸਭਾ ਵਿੱਚ ਕਿਵੇਂ ਮਦਦ ਕਰ ਸਕਦੇ ਹਾਂ?',
    heroSubtitle: 'ਉਪ-ਨਿਯਮਾਂ, ਵੋਟਿੰਗ ਅਧਿਕਾਰਾਂ, ਚੋਣਾਂ ਅਤੇ ਰਸਮੀ ਸ਼ਿਕਾਇਤ ਪੱਤਰ ਆਸਾਨੀ ਨਾਲ ਤਿਆਰ ਕਰੋ।',
    askCardTitle: 'ਸਵਾਲ ਪੁੱਛੋ',
    askCardDesc: 'ਨਿਯਮਾਂ ਅਤੇ ਚੋਣ ਕਾਨੂੰਨਾਂ ਬਾਰੇ ਸਪੱਸ਼ਟ ਜਵਾਬ ਪ੍ਰਾਪਤ ਕਰੋ।',
    guidedCardTitle: 'ਮਾਰਗਦਰਸ਼ਨ ਕਾਰਜ',
    guidedCardDesc: 'ਸਹਿਕਾਰੀ ਕਾਰਜਾਂ ਨੂੰ ਕਦਮ-ਦਰ-ਕਦਮ ਪੂਰਾ ਕਰੋ।',
    grievanceCardTitle: 'ਸ਼ਿਕਾਇਤ ਦਰਜ ਕਰੋ',
    grievanceCardDesc: 'ਅਧਿਕਾਰਤ ਨਿਯਮਾਂ ਅਨੁਸਾਰ ਸ਼ਿਕਾਇਤ ਪੱਤਰ ਤਿਆਰ ਕਰੋ।',
    rightsCardTitle: 'ਮੇਰੇ ਅਧਿਕਾਰ',
    rightsCardDesc: 'ਆਪਣੇ ਕਾਨੂੰਨੀ ਅਧਿਕਾਰਾਂ ਅਤੇ ਜ਼ਿੰਮੇਵਾਰੀਆਂ ਨੂੰ ਜਾਣੋ।',
    voiceCardTitle: 'ਆਵਾਜ਼ ਸਹਾਇਕ',
    voiceCardDesc: 'ਆਪਣੀ ਮਾਂ-ਬੋਲੀ ਵਿੱਚ ਸਹਿਜਤਾ ਨਾਲ ਬੋਲੋ।',
    knowledgeCardTitle: 'ਨਿਯਮ ਅਤੇ ਸਰੋਤ',
    knowledgeCardDesc: 'ਸਹਿਕਾਰੀ ਐਕਟ ਅਤੇ ਦਸਤਾਵੇਜ਼ ਵੇਖੋ।',
    activeWorkflowNotice: 'ਤੁਹਾਡਾ ਇੱਕ ਕਾਰਜ ਜਾਰੀ ਹੈ',
    resumeTaskBtn: 'ਜਾਰੀ ਰੱਖੋ',
    sampleQuestionsLabel: 'ਆਮ ਪੁੱਛੇ ਜਾਣ ਵਾਲੇ ਸਵਾਲ:',
    typePlaceholder: 'ਆਪਣੀ ਬੋਲੀ ਵਿੱਚ ਪੁੱਛੋ (ਜਿਵੇਂ: ਮੇਰਾ ਵੋਟਿੰਗ ਅਧਿਕਾਰ ਕੀ ਹੈ?)...',
    sendBtn: 'ਭੇਜੋ',
    voiceBtn: 'ਆਵਾਜ਼ ਇਨਪੁੱਟ',
    clearChatBtn: 'ਗੱਲਬਾਤ ਸਾਫ਼ ਕਰੋ',
    sourcesLabel: 'ਤਸਦੀਕਸ਼ੁਦਾ ਸਰੋਤ',
    demoDataBadge: 'ਡੈਮੋ ਨੌਲੇਜ ਬੇਸ',
    disclaimerText: 'ਨੋਟ: ਇਹ ਜਾਣਕਾਰੀ ਉਪ-ਨਿਯਮਾਂ ਅਨੁਸਾਰ ਹੈ, ਅਧਿਕਾਰਤ ਕਾਨੂੰਨੀ ਸਲਾਹ ਦਾ ਬਦਲ ਨਹੀਂ ਹੈ।',
    closeBtn: 'ਬੰਦ ਕਰੋ',
    backBtn: 'ਪਿੱਛੇ',
    continueBtn: 'ਅੱਗੇ',
    cancelBtn: 'ਰੱਦ ਕਰੋ',
    saveBtn: 'ਸੰਭਾਲੋ',
    editBtn: 'ਸੋਧੋ',
    downloadPdfBtn: 'PDF ਡਾਊਨਲੋਡ',
    downloadTxtBtn: 'TXT ਡਾਊਨਲੋਡ',
    suggestedQ1: 'ਮੇਰਾ ਵੋਟਿੰਗ ਅਧਿਕਾਰ ਕੀ ਹੈ?',
    suggestedQ2: 'ਮੈਂਬਰ ਵਜੋਂ ਮੇਰੇ ਕੀ ਅਧਿਕਾਰ ਹਨ?',
    suggestedQ3: 'ਪ੍ਰਬੰਧਕ ਕਮੇਟੀ ਵਿਰੁੱਧ ਸ਼ਿਕਾਇਤ ਕਿਵੇਂ ਦਰਜ ਕਰੀਏ?',
    suggestedQ4: 'ਸਹਿਕਾਰੀ ਸਭਾ ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਲਈ ਕੀ ਦਸਤਾਵੇਜ਼ ਚਾਹੀਦੇ ਹਨ?',
    voiceListening: 'ਸੁਣ ਰਹੇ ਹਾਂ...',
    voiceProcessing: 'ਸਮਝ ਰਹੇ ਹਾਂ...',
    voiceSpeaking: 'ਜਵਾਬ ਦੇ ਰਹੇ ਹਾਂ...',
    voiceIdle: 'ਬੋਲਣ ਲਈ ਮਾਈਕ ਦਬਾਓ',
  },
  or: {
    appName: 'କୋ-ଅପ୍ ସହାୟକ (Co-opSahayak)',
    appSubtitle: 'ସମବାୟ ଏବଂ ଆଇନଗତ ସହାୟତା କେନ୍ଦ୍ର',
    navHome: 'ମୂଳ ପୃଷ୍ଠା',
    navAsk: 'ସହାୟକଙ୍କୁ ପଚାରନ୍ତୁ',
    navGuided: 'ମାର୍ଗଦର୍ଶିତ କାର୍ଯ୍ୟ',
    navRights: 'ମୋର ଅଧିକାର',
    navGrievance: 'ଅଭିଯୋଗ ଦାଖଲ କରନ୍ତୁ',
    navKnowledge: 'ନିୟମାବଳୀ ଓ ଉତ୍ସ',
    navVoice: 'ଭଏସ୍ ସହାୟକ',
    navProfile: 'ମୋର ପ୍ରୋଫାଇଲ୍',
    navSettings: 'ସେଟିଙ୍ଗ୍ସ',
    welcomeHero: 'ଆଜି ଆପଣଙ୍କ ସମବାୟ ସମିତି ସମ୍ବନ୍ଧରେ ଆମେ କିପରି ସାହାଯ୍ୟ କରିପାରିବା?',
    heroSubtitle: 'ଉପ-ନିୟମ, ଭୋଟ୍ ଅଧିକାର, ନିର୍ବାଚନ ନିୟମ ବୁଝନ୍ତୁ ଏବଂ ବିଧିବଦ୍ଧ ଅଭିଯୋଗ ପତ୍ର ପ୍ରସ୍ତୁତ କରନ୍ତୁ।',
    askCardTitle: 'ପ୍ରଶ୍ନ ପଚାରନ୍ତୁ',
    askCardDesc: 'ନିୟମ ଓ ଭୋଟିଂ ନିୟମାବଳୀ ଉପରେ ସ୍ପଷ୍ଟ ଉତ୍ତର ପାଆନ୍ତୁ।',
    guidedCardTitle: 'ମାର୍ଗଦର୍ଶିତ କାର୍ଯ୍ୟ',
    guidedCardDesc: 'ସମବାୟ ପ୍ରକ୍ରିୟାକୁ ପର୍ଯ୍ୟାୟକ୍ରମେ ସମ୍ପୂର୍ଣ୍ଣ କରନ୍ତୁ।',
    grievanceCardTitle: 'ଅଭିଯୋଗ ଦାଖଲ କରନ୍ତୁ',
    grievanceCardDesc: 'ବିଧିସମ୍ମତ ଅଭିଯୋଗ ପତ୍ର ସହଜରେ ପ୍ରସ୍ତୁତ କରନ୍ତୁ।',
    rightsCardTitle: 'ମୋର ଅଧିକାର',
    rightsCardDesc: 'ଆପଣଙ୍କର ଆଇନଗତ ଅଧିକାର ଏବଂ ଦାୟିତ୍ୱ ଜାଣନ୍ତୁ।',
    voiceCardTitle: 'ଭଏସ୍ ସହାୟକ',
    voiceCardDesc: 'ନିଜ ମାତୃଭାଷାରେ ସ୍ୱାଭାବିକ ଭାବରେ କଥା ହୁଅନ୍ତୁ।',
    knowledgeCardTitle: 'ନିୟମାବଳୀ ଓ ଉତ୍ସ',
    knowledgeCardDesc: 'ସମବାୟ ଆଇନ ଏବଂ ବାଇ-ଲ’ ଯାଞ୍ଚ କରନ୍ତୁ।',
    activeWorkflowNotice: 'ଗୋଟିଏ କାର୍ଯ୍ୟ ପ୍ରଗତିରେ ଅଛି',
    resumeTaskBtn: 'କାର୍ଯ୍ୟ ଜାରି ରଖନ୍ତୁ',
    sampleQuestionsLabel: 'ବାରମ୍ବାର ପଚରାଯାଉଥିବା ପ୍ରଶ୍ନ:',
    typePlaceholder: 'ନିଜ ଭାଷାରେ ପଚାରନ୍ତୁ (ଯଥା: ମୋର ଭୋଟ୍ ଅଧିକାର କ’ଣ?)...',
    sendBtn: 'ପଠାନ୍ତୁ',
    voiceBtn: 'ଭଏସ୍ ଇନପୁଟ୍',
    clearChatBtn: 'ଚାଟ୍ ପରିଷ୍କାର କରନ୍ତୁ',
    sourcesLabel: 'ପ୍ରମାଣିତ ଉତ୍ସ',
    demoDataBadge: 'ଡେମୋ ନଲେଜ୍ ବେସ୍',
    disclaimerText: 'ସୂଚନା: ଏହା ଉପ-ନିୟମ ଆଧାରିତ ମାର୍ଗଦର୍ଶନ, କୌଣସି ଆଇନଜ୍ଞଙ୍କ ପରାମର୍ଶର ବିକଳ୍ପ ନୁହେଁ।',
    closeBtn: 'ବନ୍ଦ କରନ୍ତୁ',
    backBtn: 'ପଛକୁ',
    continueBtn: 'ଆଗକୁ',
    cancelBtn: 'ବାତିଲ୍',
    saveBtn: 'ସାଇତନ୍ତୁ',
    editBtn: 'ସଂଶୋଧନ',
    downloadPdfBtn: 'PDF ଡାଉନଲୋଡ୍',
    downloadTxtBtn: 'TXT ଡାଉନଲୋଡ୍',
    suggestedQ1: 'ମୋର ଭୋଟ୍ ଅଧିକାର କ’ଣ?',
    suggestedQ2: 'ସଦସ୍ୟ ଭାବରେ ମୋର ଅଧିକାର କ’ଣ?',
    suggestedQ3: 'କମିଟି ବିରୁଦ୍ଧରେ ଅଭିଯୋଗ କିପରି କରିବି?',
    suggestedQ4: 'ସମବାୟ ପଞ୍ଜୀକରଣ ପାଇଁ କ’ଣ ଦଲିଲ ଆବଶ୍ୟକ?',
    voiceListening: 'ଶୁଣୁଛୁ...',
    voiceProcessing: 'ବୁଝୁଛୁ...',
    voiceSpeaking: 'ଉତ୍ତର ଦେଉଛୁ...',
    voiceIdle: 'କହିବା ପାଇଁ ମାଇକ୍ ଦବାନ୍ତୁ',
  },
  as: {
    appName: 'কো-অপাৰেটিভ সহায়ক (Co-opSahayak)',
    appSubtitle: 'সমবায় আৰু আইনী সাহায্য কেন্দ্ৰ',
    navHome: 'মূল পৃষ্ঠা',
    navAsk: 'সহায়কক সোধক',
    navGuided: 'নিৰ্দেশিত কাম',
    navRights: 'মোৰ অধিকাৰ',
    navGrievance: 'অভিযোগ দাখিল কৰক',
    navKnowledge: 'আইন আৰু উৎস',
    navVoice: 'ভইচ সহায়ক',
    navProfile: 'মোৰ প্ৰফাইল',
    navSettings: 'ছেটিংছ',
    welcomeHero: 'আজি আপোনাৰ সমবায় সম্পৰ্কীয় কামত আমি কেনেদৰে সহায় কৰিব পাৰোঁ?',
    heroSubtitle: 'নিয়মাৱলী, সদস্য অধিকাৰ, নিৰ্বাচন বুজি লওক আৰু চৰকাৰী অভিযোগ পত্ৰ প্ৰস্তুত কৰক।',
    askCardTitle: 'প্ৰশ্ন সোধক',
    askCardDesc: 'আইন আৰু ভোটদানৰ নিয়মৰ বিষয়ে স্পষ্ট উত্তৰ পাওক।',
    guidedCardTitle: 'নিৰ্দেশিত কাম',
    guidedCardDesc: 'সমবায় পদ্ধতিসমূহ ধাপে ধাপে সম্পূৰ্ণ কৰক।',
    grievanceCardTitle: 'অভিযোগ দাখিল কৰক',
    grievanceCardDesc: 'আইনী নিয়ম অনুসৰি অভিযোগ পত্ৰ প্ৰস্তুত কৰক।',
    rightsCardTitle: 'মোৰ অধিকাৰ',
    rightsCardDesc: 'আপোনাৰ বিধিসন্মত অধিকাৰ আৰু দায়িত্ব জানক।',
    voiceCardTitle: 'ভইচ সহায়ক',
    voiceCardDesc: 'আপোনাৰ নিজৰ ভাষাত কথা কৈ উত্তৰ লওক।',
    knowledgeCardTitle: 'আইন আৰু উৎস',
    knowledgeCardDesc: 'সমবায় বিধি আৰু আইনসমূহ পৰীক্ষা কৰক।',
    activeWorkflowNotice: 'এটা কাম প্ৰক্ৰিয়াধীন হৈ আছে',
    resumeTaskBtn: 'কাম অব্যাহত ৰাখক',
    sampleQuestionsLabel: 'সঘনাই সোধা প্ৰশ্নসমূহ:',
    typePlaceholder: 'আপোনাৰ ভাষাত সোধক (যেনে: মোৰ ভোটৰ অধিকাৰ কি?)...',
    sendBtn: 'প্ৰেৰণ কৰক',
    voiceBtn: 'ভইচ ইনপুট',
    clearChatBtn: 'চেট মচক',
    sourcesLabel: 'প্ৰমাণিত উৎসসমূহ',
    demoDataBadge: 'ডেমো জ্ঞান ভাণ্ডাৰ',
    disclaimerText: 'টোকা: এই সহায়কে কেৱল উপ-আইনভিত্তিক তথ্য প্ৰদান কৰে, এয়া কোনো আনুষ্ঠানিক আইনী পৰামৰ্শ নহয়।',
    closeBtn: 'বন্ধ কৰক',
    backBtn: 'পিছলৈ',
    continueBtn: 'আগবাঢ়ক',
    cancelBtn: 'বাতিল',
    saveBtn: 'সংৰক্ষণ কৰক',
    editBtn: 'সম্পাদনা কৰক',
    downloadPdfBtn: 'PDF ডাউনলোড',
    downloadTxtBtn: 'TXT ডাউনলোড',
    suggestedQ1: 'মোৰ ভোটৰ অধিকাৰ কি?',
    suggestedQ2: 'সদস্য হিচাপে মোৰ অধিকাৰ কি কি?',
    suggestedQ3: 'পৰিচালনা সমিতিৰ বিৰুদ্ধে কেনেকৈ অভিযোগ কৰিব?',
    suggestedQ4: 'সমবায় পঞ্জীয়নৰ বাবে কি কি নথি লাগিব?',
    voiceListening: 'শুনি আছোঁ...',
    voiceProcessing: 'বুজি আছোঁ...',
    voiceSpeaking: 'উত্তৰ দি আছোঁ...',
    voiceIdle: 'কথা ক’বলৈ মাইকত টিপক',
  },
};